In [4]:

import random, numpy as np
m_real = []
n = 11
for i in range(n):
    m_row = []
    for j in range(n):
        m_row.append(random.randint(-3, 3))
    m_real.append(m_row)

m_real = np.array(m_real)
print(m_real)

[[-1 -3  1  2 -2  0  2 -3 -1  3 -3]
 [-2  1 -1  1  1  2 -2  3  3 -3 -1]
 [-2  0 -1  2 -1 -3 -2  2  1 -1 -2]
 [-2  3  1  0  0 -1 -2 -1 -3  0  0]
 [ 3 -2  0  0  2 -1 -3 -3 -3 -3  0]
 [ 2 -2 -2 -1  2  0 -1  3  1  1 -3]
 [ 2  1  2  0 -3 -3 -1 -3 -2  2 -3]
 [ 3 -1  1 -3  1  3  0  3  3 -1  1]
 [ 3 -3  3 -2  3  1 -3  3  3 -2 -3]
 [-3 -3  3  3 -3 -2 -3  3 -3  3 -2]
 [ 1  1  0  2 -1  2  1 -2  2  0  3]]


In [12]:
#Генерируем столбец B для матрицы с действительными числами
import random, numpy as np
b_real = []
n = 11
for i in range(1):
    b_row = []
    for j in range(n):
        b_row.append(random.randint(-3, 3))
    b_real.append(b_row)

b_real = np.array(b_real)
print(b_real)

[[-1 -3  1 -2  3  1  3 -2 -1 -2  1]]


In [5]:
np.linalg.det(m_real)

3713037.000000008

In [10]:
m_complex = []
n = 11
for i in range(n):
    m_row = []
    for j in range(n):
        x = complex(random.randint(-3, 3), random.randint(-3, 3))
        m_row.append(x)
    m_complex.append(m_row)
m_complex = np.array(m_complex)    
print(m_complex)
    


    

[[ 3.+3.j -1.+3.j -1.-2.j  3.+1.j  1.-3.j -3.-3.j  2.-2.j  3.+1.j -2.+0.j
   3.+3.j  1.-2.j]
 [-1.+2.j  2.-1.j  0.-2.j  2.+1.j  0.-3.j  0.-3.j  3.+3.j -1.+1.j -1.+3.j
  -1.+3.j  1.+2.j]
 [-3.+0.j -1.+2.j -1.-2.j  3.+1.j -1.+0.j  2.+2.j -3.-2.j -2.+0.j -2.-3.j
   0.+3.j  3.+2.j]
 [ 0.+3.j -1.+3.j  1.-3.j -1.+3.j  1.-3.j -1.+1.j -1.+3.j  3.-2.j  2.+3.j
   3.+2.j  0.+0.j]
 [ 0.+2.j  2.+3.j  2.+2.j  2.-2.j  0.-1.j  2.-1.j -2.+3.j  2.+3.j -3.-2.j
   2.-3.j  2.+0.j]
 [-3.-2.j -3.+2.j -2.+3.j -1.-2.j -1.+0.j -3.-1.j -1.+0.j  3.+0.j  1.+3.j
   0.+1.j  3.+1.j]
 [-2.-2.j -2.+0.j -1.+1.j  0.+0.j  0.+1.j  3.+3.j  3.-1.j  1.+2.j  2.+2.j
   2.-1.j -3.+1.j]
 [ 2.-1.j  2.-2.j  3.+2.j -1.+1.j  2.+0.j -2.+0.j -2.-3.j  0.+1.j  2.+2.j
  -2.-1.j  3.-1.j]
 [-3.+0.j -2.-1.j -2.+1.j -2.+1.j -2.-2.j  2.-2.j  3.+0.j  1.+0.j -2.-3.j
   0.+3.j  1.+2.j]
 [ 0.+1.j  2.+1.j  1.-1.j -1.+2.j -3.+2.j  3.-3.j  2.-2.j -2.+3.j -2.+2.j
   3.+3.j  1.-2.j]
 [ 0.-1.j  3.-1.j  0.+2.j  1.-3.j -1.-3.j -1.+1.j  2.+1.j -3.+2.j  2.-

In [13]:
b_complex = []
n = 11
for i in range(n):
    b_row = []
    for j in range(1):
        x = complex(random.randint(-3, 3), random.randint(-3, 3))
        b_row.append(x)
    b_complex.append(b_row)
b_complex = np.array(b_complex)    
print(b_complex)

[[-3.+1.j]
 [ 3.+1.j]
 [ 3.+3.j]
 [ 3.+2.j]
 [-1.+1.j]
 [-1.+3.j]
 [ 3.+3.j]
 [-1.+0.j]
 [-1.-2.j]
 [-1.+0.j]
 [-1.-2.j]]


In [11]:
np.linalg.det(m_complex)

(1257976614.000001-626563568.0000011j)

In [25]:
#Решение обратной матрицой комплексных чисел
a = np.linalg.inv(m_complex)
print("Ответ")
a

Ответ


array([[ 0.05716278+0.01396885j, -0.0289796 +0.02142165j,
        -0.10035454-0.03661387j, -0.01685027-0.09995991j,
        -0.00141391+0.04628741j,  0.0091604 +0.05968307j,
        -0.02782604+0.01114205j,  0.056064  -0.00702073j,
        -0.08398348+0.00930085j, -0.00632198+0.0844348j ,
        -0.07785502-0.06653061j],
       [ 0.02233838-0.06671421j,  0.06783307+0.05458855j,
         0.04767057-0.01616046j, -0.0321196 -0.02333783j,
         0.00354626-0.01254126j, -0.0084833 -0.09461867j,
        -0.0082244 +0.01778826j,  0.05509642+0.0506188j ,
         0.04331291+0.09147028j,  0.02652036-0.0701192j ,
        -0.01288922-0.03146188j],
       [-0.03258135-0.0448187j ,  0.08796877-0.07531063j,
        -0.08313205+0.12736079j, -0.0769416 +0.10602113j,
         0.10237432+0.0135172j , -0.04783965-0.04334306j,
        -0.00767065-0.04547932j, -0.05248395-0.08617394j,
        -0.07033447-0.01883676j,  0.05137884+0.06313128j,
        -0.06907688+0.05839134j],
       [ 0.06486841-0.012755

In [26]:
#Проверка
b = np.linalg.inv(a)
b

array([[ 3.00000000e+00+3.00000000e+00j, -1.00000000e+00+3.00000000e+00j,
        -1.00000000e+00-2.00000000e+00j,  3.00000000e+00+1.00000000e+00j,
         1.00000000e+00-3.00000000e+00j, -3.00000000e+00-3.00000000e+00j,
         2.00000000e+00-2.00000000e+00j,  3.00000000e+00+1.00000000e+00j,
        -2.00000000e+00-4.44089210e-16j,  3.00000000e+00+3.00000000e+00j,
         1.00000000e+00-2.00000000e+00j],
       [-1.00000000e+00+2.00000000e+00j,  2.00000000e+00-1.00000000e+00j,
         4.44089210e-15-2.00000000e+00j,  2.00000000e+00+1.00000000e+00j,
         8.88178420e-16-3.00000000e+00j, -8.88178420e-16-3.00000000e+00j,
         3.00000000e+00+3.00000000e+00j, -1.00000000e+00+1.00000000e+00j,
        -1.00000000e+00+3.00000000e+00j, -1.00000000e+00+3.00000000e+00j,
         1.00000000e+00+2.00000000e+00j],
       [-3.00000000e+00-3.27515792e-15j, -1.00000000e+00+2.00000000e+00j,
        -1.00000000e+00-2.00000000e+00j,  3.00000000e+00+1.00000000e+00j,
        -1.00000000e+00+1.24

In [14]:
#Решение способом обратной матрицы 
import numpy as np
A=np.array([[-1, -3,  1,  2, -2,  0,  2, -3, -1,  3, -3],
 [-2,  1, -1,  1,  1,  2, -2,  3,  3, -3, -1],
 [-2,  0, -1,  2, -1, -3, -2,  2,  1, -1, -2],
 [-2,  3,  1,  0,  0, -1, -2, -1, -3,  0,  0],
 [ 3, -2,  0,  0,  2, -1, -3, -3, -3, -3,  0],
 [ 2, -2, -2, -1,  2,  0, -1,  3,  1,  1, -3],
 [ 2,  1,  2,  0, -3, -3, -1, -3, -2,  2, -3],
 [ 3, -1,  1, -3,  1,  3,  0,  3,  3, -1,  1],
 [ 3, -3,  3, -2,  3,  1, -3,  3,  3, -2, -3],
 [-3, -3,  3,  3, -3, -2, -3,  3, -3,  3, -2],
 [ 1,  1,  0,  2, -1,  2,  1, -2,  2,  0,  3]]) #создание матрицы 
B=np.array([ 1, -1,  0, -1,  1,  0,  2, -3,  0,  0,  2]) #создаю матрицу столбца свободных членов 
det = np.linalg.det(A) 
if det==0:
    print ("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
    a_inv = np.linalg.inv(A) 
X=np.dot(a_inv, B)
    
print ("Решение системы:\n", X)

Решение системы:
 [ 2.33624793  1.58677735  1.50022583  3.61393301  1.21307221 -0.2711632
  3.10349614  1.82252749 -1.72343152 -1.35842654 -1.13569027]


In [15]:
print("Проверка:") 
for i in range(11): 
    otv = A[i][0]*X[0] + A[i][1]*X[1] + A[i][2]*X[2] + A[i][3]*X[3]+ A[i][4]*X[4] + A[i][5]*X[5]+ A[i][6]*X[6]+ A[i][7]*X[7]+ A[i][8]*X[8]+ A[i][9]*X[9]+ A[i][10]*X[10]
    print(otv, B[i])

Проверка:
1.0000000000000044 1
-1.0000000000000044 -1
2.6645352591003757e-15 0
-1.0000000000000009 -1
1.0 1
3.552713678800501e-15 0
2.0000000000000018 2
-3.0000000000000027 -3
-4.440892098500626e-16 0
0.0 0
1.9999999999999947 2


In [18]:
import numpy as np
A=np.array([[ 3.+3.j, -1.+3.j, -1.-2.j,  3.+1.j,  1.-3.j, -3.-3.j,  2.-2.j,  3.+1.j, -2.+0.j,
   3.+3.j,  1.-2.j],
 [-1.+2.j,  2.-1.j,  0.-2.j,  2.+1.j,  0.-3.j,  0.-3.j,  3.+3.j, -1.+1.j, -1.+3.j,
  -1.+3.j,  1.+2.j],
 [-3.+0.j, -1.+2.j, -1.-2.j,  3.+1.j, -1.+0.j,  2.+2.j, -3.-2.j, -2.+0.j, -2.-3.j,
   0.+3.j,  3.+2.j],
 [ 0.+3.j, -1.+3.j,  1.-3.j, -1.+3.j,  1.-3.j, -1.+1.j, -1.+3.j,  3.-2.j,  2.+3.j,
   3.+2.j,  0.+0.j],
 [ 0.+2.j, 2.+3.j,  2.+2.j,  2.-2.j,  0.-1.j,  2.-1.j, -2.+3.j,  2.+3.j, -3.-2.j,
   2.-3.j,  2.+0.j]
 [-3.-2.j, -3.+2.j, -2.+3.j, -1.-2.j, -1.+0.j, -3.-1.j, -1.+0.j,  3.+0.j,  1.+3.j,
   0.+1.j,  3.+1.j],
 [-2.-2.j, -2.+0.j, -1.+1.j,  0.+0.j,  0.+1.j,  3.+3.j,  3.-1.j , 1.+2.j,  2.+2.j,
   2.-1.j, -3.+1.j],
 [ 2.-1.j,  2.-2.j,  3.+2.j, -1.+1.j,  2.+0.j, -2.+0.j, -2.-3.j,  0.+1.j,  2.+2.j,
  -2.-1.j,  3.-1.j],
 [-3.+0.j, -2.-1.j, -2.+1.j, -2.+1.j, -2.-2.j,  2.-2.j,  3.+0.j,  1.+0.j, -2.-3.j,
   0.+3.j,  1.+2.j],
 [ 0.+1.j,  2.+1.j,  1.-1.j, -1.+2.j, -3.+2.j,  3.-3.j,  2.-2.j, -2.+3.j, -2.+2.j,
   3.+3.j,  1.-2.j],
 [ 0.-1.j,  3.-1.j,  0.+2.j,  1.-3.j, -1.-3.j, -1.+1.j,  2.+1.j, -3.+2.j,  2.-1.j,
  -3.-3.j, -2.-3.j]])
B=np.array([[-3.+1.j],
 [ 3.+1.j],
 [ 3.+3.j],
 [ 3.+2.j],
 [-1.+1.j],
 [-1.+3.j],
 [ 3.+3.j],
 [-1.+0.j],
 [-1.-2.j],
 [-1.+0.j],
 [-1.-2.j]])
det = np.linalg.det(A)
if det==0:
    print ("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
    a_inv = np.linalg.inv(A)
X=np.dot(a_inv, B)
print ("Решение системы:\n", X)

<>:10: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:10: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-18-0773e33551f3>:10: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [ 0.+2.j, 2.+3.j,  2.+2.j,  2.-2.j,  0.-1.j,  2.-1.j, -2.+3.j,  2.+3.j, -3.-2.j,


TypeError: list indices must be integers or slices, not tuple

In [19]:
#Вычислите LU-разложение своих матриц (действительной и комплексной из Задания 01). Прямо проверьте правильность полученных результатов. 
import numpy as np
import scipy.linalg as la
M = np.array([[-1, -3,  1,  2, -2,  0,  2, -3, -1,  3, -3],
 [-2,  1, -1,  1,  1,  2, -2,  3,  3, -3, -1],
 [-2,  0, -1,  2, -1, -3, -2,  2,  1, -1, -2],
 [-2,  3,  1,  0,  0, -1, -2, -1, -3,  0,  0],
 [ 3, -2,  0,  0,  2, -1, -3, -3, -3, -3,  0],
 [ 2, -2, -2, -1,  2,  0, -1,  3,  1,  1, -3],
 [ 2,  1,  2,  0, -3, -3, -1, -3, -2,  2, -3],
 [ 3, -1,  1, -3,  1,  3,  0,  3,  3, -1,  1],
 [ 3, -3,  3, -2,  3,  1, -3,  3,  3, -2, -3],
 [-3, -3,  3,  3, -3, -2, -3,  3, -3,  3, -2],
 [ 1,  1,  0,  2, -1,  2,  1, -2,  2,  0,  3]])
P, L, U = la.lu(M)
M

array([[-1, -3,  1,  2, -2,  0,  2, -3, -1,  3, -3],
       [-2,  1, -1,  1,  1,  2, -2,  3,  3, -3, -1],
       [-2,  0, -1,  2, -1, -3, -2,  2,  1, -1, -2],
       [-2,  3,  1,  0,  0, -1, -2, -1, -3,  0,  0],
       [ 3, -2,  0,  0,  2, -1, -3, -3, -3, -3,  0],
       [ 2, -2, -2, -1,  2,  0, -1,  3,  1,  1, -3],
       [ 2,  1,  2,  0, -3, -3, -1, -3, -2,  2, -3],
       [ 3, -1,  1, -3,  1,  3,  0,  3,  3, -1,  1],
       [ 3, -3,  3, -2,  3,  1, -3,  3,  3, -2, -3],
       [-3, -3,  3,  3, -3, -2, -3,  3, -3,  3, -2],
       [ 1,  1,  0,  2, -1,  2,  1, -2,  2,  0,  3]])

In [20]:
P

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [21]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.66666667, -0.46666667,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.        ,  0.2       ,  0.70588235,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.66666667, -0.33333333,  0.58823529, -0.04918033,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.33333333,  0.29411765, -0.72131148,  0.67206478,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.   

In [22]:
U

array([[ 3.        , -2.        ,  0.        ,  0.        ,  2.        ,
        -1.        , -3.        , -3.        , -3.        , -3.        ,
         0.        ],
       [ 0.        , -5.        ,  3.        ,  3.        , -1.        ,
        -3.        , -6.        ,  0.        , -6.        ,  0.        ,
        -2.        ],
       [ 0.        ,  0.        ,  3.4       ,  1.4       , -4.8       ,
        -3.73333333, -1.8       , -1.        , -2.8       ,  4.        ,
        -3.93333333],
       [ 0.        ,  0.        ,  0.        , -3.58823529,  4.58823529,
         5.23529412,  2.47058824,  6.70588235,  9.17647059, -1.82352941,
         0.17647059],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  4.04918033,
        -0.21311475, -4.81967213, -2.08196721, -4.90163934, -4.44262295,
         1.6557377 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         6.35087719,  5.55060729,  5.53036437, 11.73684211,  1.49392713,
         2.504

In [23]:
#Проверка
M

array([[-1, -3,  1,  2, -2,  0,  2, -3, -1,  3, -3],
       [-2,  1, -1,  1,  1,  2, -2,  3,  3, -3, -1],
       [-2,  0, -1,  2, -1, -3, -2,  2,  1, -1, -2],
       [-2,  3,  1,  0,  0, -1, -2, -1, -3,  0,  0],
       [ 3, -2,  0,  0,  2, -1, -3, -3, -3, -3,  0],
       [ 2, -2, -2, -1,  2,  0, -1,  3,  1,  1, -3],
       [ 2,  1,  2,  0, -3, -3, -1, -3, -2,  2, -3],
       [ 3, -1,  1, -3,  1,  3,  0,  3,  3, -1,  1],
       [ 3, -3,  3, -2,  3,  1, -3,  3,  3, -2, -3],
       [-3, -3,  3,  3, -3, -2, -3,  3, -3,  3, -2],
       [ 1,  1,  0,  2, -1,  2,  1, -2,  2,  0,  3]])

In [24]:
P.dot(L.dot(U))

array([[-1.00000000e+00, -3.00000000e+00,  1.00000000e+00,
         2.00000000e+00, -2.00000000e+00,  0.00000000e+00,
         2.00000000e+00, -3.00000000e+00, -1.00000000e+00,
         3.00000000e+00, -3.00000000e+00],
       [-2.00000000e+00,  1.00000000e+00, -1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
        -2.00000000e+00,  3.00000000e+00,  3.00000000e+00,
        -3.00000000e+00, -1.00000000e+00],
       [-2.00000000e+00,  0.00000000e+00, -1.00000000e+00,
         2.00000000e+00, -1.00000000e+00, -3.00000000e+00,
        -2.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        -1.00000000e+00, -2.00000000e+00],
       [-2.00000000e+00,  3.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -2.77555756e-17, -1.00000000e+00,
        -2.00000000e+00, -1.00000000e+00, -3.00000000e+00,
        -4.44089210e-16, -1.11022302e-16],
       [ 3.00000000e+00, -2.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00, -1.00000000e+00,
  

In [27]:
#Вычислите QR-разложение своих матриц (действительной и комплексной из Задания 01). Проверьте правильность полученных результатов. 
A = np.matrix("-1 -3  1  2 -2  0  2 -3 -1  3 -3;-2  1 -1  1  1  2 -2  3  3 -3 -1;-2  0 -1  2 -1 -3 -2  2  1 -1 -2; -2  3  1  0  0 -1 -2 -1 -3  0  0; 3 -2  0  0  2 -1 -3 -3 -3 -3  0;  2 -2 -2 -1  2  0 -1  3  1  1 -3; 2  1  2  0 -3 -3 -1 -3 -2  2 -3; 3 -1  1 -3  1  3  0  3  3 -1  1; 3 -3  3 -2  3  1 -3  3  3 -2 -3; -3 -3  3  3 -3 -2 -3  3 -3  3 -2; 1  1  0  2 -1  2  1 -2  2  0  3")
q, r = np.linalg.qr(A)
A

matrix([[-1, -3,  1,  2, -2,  0,  2, -3, -1,  3, -3],
        [-2,  1, -1,  1,  1,  2, -2,  3,  3, -3, -1],
        [-2,  0, -1,  2, -1, -3, -2,  2,  1, -1, -2],
        [-2,  3,  1,  0,  0, -1, -2, -1, -3,  0,  0],
        [ 3, -2,  0,  0,  2, -1, -3, -3, -3, -3,  0],
        [ 2, -2, -2, -1,  2,  0, -1,  3,  1,  1, -3],
        [ 2,  1,  2,  0, -3, -3, -1, -3, -2,  2, -3],
        [ 3, -1,  1, -3,  1,  3,  0,  3,  3, -1,  1],
        [ 3, -3,  3, -2,  3,  1, -3,  3,  3, -2, -3],
        [-3, -3,  3,  3, -3, -2, -3,  3, -3,  3, -2],
        [ 1,  1,  0,  2, -1,  2,  1, -2,  2,  0,  3]])

In [28]:
q

matrix([[-0.13130643,  0.49058319,  0.02146769,  0.18804426,  0.21724624,
         -0.23486495,  0.3416009 , -0.39275424, -0.3863745 ,  0.37895654,
          0.2001684 ],
        [-0.26261287, -0.07267899, -0.13882436,  0.00269731, -0.38699873,
         -0.30770426, -0.53479918, -0.1847889 , -0.40900818,  0.12492474,
         -0.39871275],
        [-0.26261287,  0.07787035, -0.19546892,  0.19909535, -0.00866292,
          0.41746903, -0.2342742 ,  0.35181521, -0.46973131, -0.17856197,
          0.49150582],
        [-0.26261287, -0.37377767,  0.35997918, -0.15189239, -0.31453188,
          0.2006511 , -0.05520518, -0.28618325,  0.1633942 ,  0.43893662,
          0.44177571],
        [ 0.3939193 ,  0.18429316, -0.10922156,  0.34781338, -0.36348527,
          0.31319132, -0.10797346, -0.57508822,  0.10097207, -0.29991735,
          0.07224457],
        [ 0.26261287,  0.22322833, -0.49609184, -0.04009024,  0.04881866,
          0.17279551, -0.29964785,  0.15938775,  0.27914153,  0.6385461

In [29]:
r

matrix([[ 7.61577311e+00, -1.96959649e+00,  5.25225731e-01,
         -4.20180585e+00,  3.41396725e+00,  1.96959649e+00,
         -2.62612866e-01, -9.19145030e-01,  2.23220936e+00,
         -2.10090293e+00,  4.44089210e-16],
        [ 0.00000000e+00, -6.64234068e+00,  1.95195005e+00,
          1.39647491e+00, -1.09018487e-01, -5.84027609e-01,
         -1.72872172e+00,  2.83188499e+00, -3.60799279e-01,
          1.82735750e+00, -4.21538150e+00],
        [ 0.00000000e+00,  0.00000000e+00,  5.18787326e+00,
          9.27253347e-02, -2.42494452e+00, -1.13620548e+00,
         -2.02157801e+00, -9.72448474e-01, -2.21056897e+00,
          1.64547923e+00, -1.11255337e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          4.04797325e+00, -3.03314184e+00, -1.92768146e+00,
         -1.23983100e-01, -4.87319294e+00, -1.95452546e+00,
          1.10375662e+00,  2.44526410e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00, -4.03145597e+00, -

In [30]:
#Проверка
q.dot(r)

matrix([[-1.00000000e+00, -3.00000000e+00,  1.00000000e+00,
          2.00000000e+00, -2.00000000e+00,  4.44089210e-16,
          2.00000000e+00, -3.00000000e+00, -1.00000000e+00,
          3.00000000e+00, -3.00000000e+00],
        [-2.00000000e+00,  1.00000000e+00, -1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         -2.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         -3.00000000e+00, -1.00000000e+00],
        [-2.00000000e+00,  2.22044605e-16, -1.00000000e+00,
          2.00000000e+00, -1.00000000e+00, -3.00000000e+00,
         -2.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         -1.00000000e+00, -2.00000000e+00],
        [-2.00000000e+00,  3.00000000e+00,  1.00000000e+00,
         -2.22044605e-16,  0.00000000e+00, -1.00000000e+00,
         -2.00000000e+00, -1.00000000e+00, -3.00000000e+00,
         -1.33226763e-15,  2.22044605e-16],
        [ 3.00000000e+00, -2.00000000e+00,  2.22044605e-16,
         -2.22044605e-16,  2.00000000e+00, -