In [ ]:
## № 86(a) 

In [19]:
import numpy as np

In [20]:
A = np.array([[-1, -1, -1, -1],[-1, -1, -1, -1],[4, 3, 4, 2],[-2, 0, -2, 1]])
A

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [ 4,  3,  4,  2],
       [-2,  0, -2,  1]])

In [21]:
np.linalg.eig(A) 

(array([1.00001178e+00+0.00000000e+00j, 9.99994111e-01+1.02005992e-05j,
        9.99994111e-01-1.02005992e-05j, 3.70990693e-16+0.00000000e+00j]),
 array([[ 3.77962565e-01+0.00000000e+00j, -3.77965427e-01+3.85547385e-06j,
         -3.77965427e-01-3.85547385e-06j,  7.07106781e-01+0.00000000e+00j],
        [ 3.77962565e-01+0.00000000e+00j, -3.77965427e-01+3.85547385e-06j,
         -3.77965427e-01-3.85547385e-06j,  2.25346008e-15+0.00000000e+00j],
        [-3.77958113e-01+0.00000000e+00j,  3.77967653e-01-7.71092498e-06j,
          3.77967653e-01+7.71092498e-06j, -7.07106781e-01+0.00000000e+00j],
        [-7.55934034e-01+0.00000000e+00j,  7.55926402e-01+0.00000000e+00j,
          7.55926402e-01-0.00000000e+00j, -1.96164485e-15+0.00000000e+00j]]))

In [22]:
## 86(b)

In [23]:
A = np.array([[-1, -2, -2, -1],[2, 3, 2, 1],[-3, -3, 0, 0],[3, 3, 1, 1]])
A

array([[-1, -2, -2, -1],
       [ 2,  3,  2,  1],
       [-3, -3,  0,  0],
       [ 3,  3,  1,  1]])

In [24]:
np.linalg.eig(A)

(array([3.44070435e-15, 9.99999947e-01, 1.00000005e+00, 1.00000000e+00]),
 array([[-5.00000000e-01, -7.07106763e-01,  7.07106800e-01,
         -3.53343000e-02],
        [ 5.00000000e-01,  7.07106800e-01, -7.07106763e-01,
          2.29851132e-01],
        [-5.00000000e-01, -1.12049746e-07, -1.12049761e-07,
         -5.83550495e-01],
        [ 5.00000000e-01,  1.12049746e-07,  1.12049761e-07,
          7.78067326e-01]]))

In [25]:
##№ 86(c)

In [26]:
A = np.array([[0, 2, 1, 1],[1, 1, 1, 1],[-1, -2, -2, -1],[-1, -2, -1, -2]])
A

array([[ 0,  2,  1,  1],
       [ 1,  1,  1,  1],
       [-1, -2, -2, -1],
       [-1, -2, -1, -2]])

In [27]:
np.linalg.eig(A)

(array([-5.36251823e-16, -1.00000000e+00, -1.00000000e+00, -1.00000000e+00]),
 array([[ 5.00000000e-01,  8.02918932e-16,  5.79813286e-01,
         -1.88941534e-01],
        [ 5.00000000e-01, -5.77350269e-01,  1.77250919e-01,
         -4.73851171e-01],
        [-5.00000000e-01,  5.77350269e-01, -7.80148208e-01,
          3.51773427e-01],
        [-5.00000000e-01,  5.77350269e-01, -1.54166916e-01,
          7.84870448e-01]]))

In [28]:
## 86 (e)

In [29]:
A = np.array([[0, -1, 1, -1],[1, 2, -1, 1],[3, 3, -1, 2],[3, 3, -2, 3]])
A

array([[ 0, -1,  1, -1],
       [ 1,  2, -1,  1],
       [ 3,  3, -1,  2],
       [ 3,  3, -2,  3]])

In [30]:
np.linalg.eig(A)

(array([1.+2.58677832e-08j, 1.-2.58677832e-08j, 1.+1.09212341e-08j,
        1.-1.09212341e-08j]),
 array([[-0.2236068 +5.78421217e-09j, -0.2236068 -5.78421217e-09j,
          0.30862698-2.95729071e-09j,  0.30862698+2.95729071e-09j],
        [ 0.2236068 +1.28069892e-25j,  0.2236068 -1.28069892e-25j,
         -0.30862698+2.75038562e-09j, -0.30862698-2.75038562e-09j],
        [ 0.67082039+0.00000000e+00j,  0.67082039-0.00000000e+00j,
         -0.63619917+3.16368239e-09j, -0.63619917-3.16368239e-09j],
        [ 0.67082039+1.22656729e-25j,  0.67082039-1.22656729e-25j,
         -0.63619917+0.00000000e+00j, -0.63619917-0.00000000e+00j]]))

In [31]:
## 86(d)

In [32]:
A = np.array([[3, -3, -1, 2],[-2, 2, -1, 2],[2, 0, 3, 2],[-3, 3, 0, -2]])
A

array([[ 3, -3, -1,  2],
       [-2,  2, -1,  2],
       [ 2,  0,  3,  2],
       [-3,  3,  0, -2]])

In [33]:
np.linalg.eig(A)

(array([-2.,  5.,  1.,  2.]),
 array([[ 5.77350269e-01, -5.14495755e-01,  5.77350269e-01,
         -4.08248290e-01],
        [ 5.77350269e-01,  6.85994341e-01,  5.77350269e-01,
         -4.08248290e-01],
        [ 1.18066140e-17,  6.92590123e-17, -5.77350269e-01,
          8.16496581e-01],
        [-5.77350269e-01,  5.14495755e-01, -8.53528608e-16,
          6.73868592e-16]]))

In [34]:
## 86(f)

In [35]:
A = np.array([[-5, -1, 2, -1],[4, 0, -2, 1],[-4, -1, 1, -1],[4, 1, -2, 0]])
A

array([[-5, -1,  2, -1],
       [ 4,  0, -2,  1],
       [-4, -1,  1, -1],
       [ 4,  1, -2,  0]])

In [36]:
np.linalg.eig(A)

(array([-1.00000008, -0.99999992, -1.        , -1.        ]),
 array([[ 0.50000001,  0.49999999, -0.16398827, -0.10660915],
        [-0.5       , -0.5       , -0.73640594, -0.46312493],
        [ 0.5       ,  0.5       , -0.46411967, -0.00485856],
        [-0.5       , -0.5       ,  0.46411967,  0.87984441]]))