# Загородний Даниил КСиК-32

# Условие

In [71]:
#Генерируем матрицу действительных чисел
import random, numpy as np
m_real = []
n = 11
for i in range(n):
    m_row = []
    for j in range(n):
        m_row.append(random.randint(-3, 3))
    m_real.append(m_row)

m_real = np.array(m_real)
print(m_real)

[[ 0 -2 -1  3  0 -2 -3 -3  1  1  3]
 [-3  1 -2 -1 -2  3  0 -1 -1 -2  3]
 [-1  0  3 -3 -2  0  2  0  2 -2 -1]
 [ 3  0 -1 -1  3  3  3 -3  1  3  3]
 [ 3 -2  0 -1  2 -1 -1  2  0 -2 -2]
 [-1  3 -2  2  0  0  3  2  1  3  3]
 [ 0 -2 -1  3  1 -2  3  1  0  0  2]
 [-3  1  1 -3 -3  3  0  3  3 -2 -2]
 [-1  2  0 -3 -3  1  0  2 -1  2  1]
 [ 0  3  2  2 -1 -3 -3  3 -1 -3  0]
 [-3 -1  1 -1  0  0  1  1  0 -2 -2]]


In [72]:
#Генерируем  столбец свободных членов для матрицы с действительными числами
import random, numpy as np
m_real = []
n = 11
for i in range(1):
    m_row = []
    for j in range(n):
        m_row.append(random.randint(-3, 3))
    m_real.append(m_row)

m_real = np.array(m_real)
print(m_real)

[[-1  1 -2 -1 -1  2  3  3  0  2  3]]


In [2]:
#Генерируем матрицу с комплексными числами
m_complex = []
n = 11
for i in range(n):
    m_row = []
    for j in range(n):
        x = complex(random.randint(-3, 3), random.randint(-3, 3))
        m_row.append(x)
    m_complex.append(m_row)
m_complex = np.array(m_complex)    
print(m_complex)

[[-3.-2.j -3.+3.j  0.-2.j -1.+1.j  1.-2.j  2.-3.j -2.+0.j  2.-3.j -3.+1.j
  -3.-1.j  1.+2.j]
 [ 2.+0.j  1.-1.j -2.+0.j  0.-2.j  0.+1.j  0.-2.j  2.+3.j  1.+3.j  0.-3.j
  -1.+1.j  2.-1.j]
 [ 3.-1.j -2.-1.j  3.+0.j -2.+1.j  1.+1.j -1.-2.j -3.+1.j  1.+1.j  3.+1.j
  -2.-1.j  1.+0.j]
 [ 2.+3.j  3.-3.j -3.-3.j  0.+1.j -3.-1.j  3.+0.j  1.+3.j  1.-1.j  0.-2.j
   0.+2.j -1.+2.j]
 [-2.+0.j  0.-3.j  1.-1.j  0.-3.j  3.-2.j -1.+0.j  0.-3.j -1.+1.j -3.-3.j
  -1.+2.j -2.+0.j]
 [-3.+0.j  2.+3.j  2.-1.j  1.-2.j  1.+2.j  0.-1.j -1.+0.j -2.+0.j  0.+2.j
   2.+0.j  3.+3.j]
 [ 0.+0.j  0.+2.j  2.+0.j  2.+1.j  1.-1.j -1.+3.j  0.-2.j -1.+2.j  2.-3.j
  -3.+0.j -3.+3.j]
 [-2.-1.j -3.+1.j  2.+1.j -1.-1.j  0.+1.j -1.+1.j -2.+2.j  3.+1.j  0.-3.j
   0.+2.j  0.-2.j]
 [-2.+2.j -3.-2.j  3.+3.j -1.-2.j -3.+3.j -3.+2.j -2.+3.j  0.+3.j  2.-2.j
   2.+2.j  2.-3.j]
 [-3.+1.j  1.+0.j -3.+1.j  2.-1.j  2.+3.j  0.+1.j -3.+0.j -3.+0.j  2.+3.j
   2.+3.j -2.+2.j]
 [ 2.+3.j  3.+2.j -1.+2.j  3.+3.j  1.-2.j  1.+2.j  0.-3.j -1.+0.j -2.+

In [7]:
#Генерируем  столбец свободных членов для матрицы с комплексными числами
m_complex = []
n = 11
for i in range(1):
    m_row = []
    for j in range(n):
        x = complex(random.randint(-3, 3), random.randint(-3, 3))
        m_row.append(x)
    m_complex.append(m_row)
m_complex = np.array(m_complex)    
print(m_complex)

[[-3.-1.j  0.+0.j  0.-2.j  0.+2.j -3.-2.j  0.+3.j  1.+3.j  0.+3.j -3.-3.j
   1.+0.j  0.+0.j]]


# Решение матриц методом обратной матрицы

In [74]:
import numpy as np 
A=np.array[[ 0, -2, -1,  3,  0, -2, -3, -3,  1,  1,  3],
 [-3,  1, -2, -1, -2,  3,  0, -1, -1, -2,  3],
 [-1,  0,  3, -3, -2,  0,  2,  0,  2, -2, -1],
 [ 3,  0, -1, -1,  3,  3,  3, -3,  1,  3,  3],
 [ 3, -2,  0, -1,  2, -1, -1,  2,  0, -2, -2],
 [-1,  3, -2,  2,  0, 0,  3,  2,  1,  3,  3],
 [ 0, -2, -1,  3,  1, -2,  3,  1,  0,  0,  2],
 [-3, 1, 1, -3, -3,  3,  0,  3,  3, -2, -2],
 [-1,  2,  0, -3, -3,  1,  0,  2, -1,  2,  1],
 [ 0,  3,  2,  2, -1, -3, -3,  3, -1, -3,  0],
 [-3, -1,  1, -1,  0,  0,  1,  1,  0, -2, -2]] #создание матрицы 
B=np.array([-1,  1, -2, -1, -1,  2,  3,  3,  0,  2,  3]) #создаю матрицу столбца свободных членов 
det = np.linalg.det(A) 
if det==0: 
 print ("Определитель матрицы равен нулю, система имеет бесконечно много решений") 
else: 
 a_inv = np.linalg.inv(A) 
X=np.dot(a_inv, B) 
print ("Решение системы:\n", X)


TypeError: 'builtin_function_or_method' object is not subscriptable

# Проверка

In [25]:
print("Проверка:") 
for i in range(11): 
    otv = A[i][0]*X[0] + A[i][1]*X[1] + A[i][2]*X[2] + A[i][3]*X[3]+ A[i][4]*X[4] + A[i][5]*X[5]+ A[i][6]*X[6]+ A[i][7]*X[7]+ A[i][8]*X[8]+ A[i][9]*X[9]+ A[i][10]*X[10]
    print(otv, B[i])

Проверка:
-1.999999999999995 -2
-3.0000000000000036 -3
-2.886579864025407e-15 0
-0.9999999999999973 -1
-1.0000000000000007 -1
-3.0000000000000018 -3
-3.0 -3
-1.9999999999999967 -2
-3.0000000000000036 -3
-1.9999999999999958 -2
-4.440892098500626e-16 0


# Метод обратной матрицы с комплексными числами

In [10]:
import numpy as np 
A=np.array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]]) #создание матрицы 
B=np.array([-3.-1.j, 0.+0.j,  0.-2.j,  0.+2.j, -3.-2.j,  0.+3.j,  1.+3.j,  0.+3.j, -3.-3.j,
   1.+0.j,  0.+0.j]) #создаю матрицу столбца свободных членов 
det = np.linalg.det(A) 
if det==0: 
 print ("Определитель матрицы равен нулю, система имеет бесконечно много решений") 
else: 
 a_inv = np.linalg.inv(A) 
X=np.dot(a_inv, B) 
print ("Решение системы:\n", X)



Решение системы:
 [ 1.72326265+0.19162439j  2.19894081-0.49677449j -1.79768889-1.07303601j
 -0.12919282+0.82240572j  0.07532908-1.20068416j -3.17332842-1.24936017j
 -3.27124596-0.59723819j  0.43508882+2.33494833j -1.82424066+2.09247407j
  0.13168118+2.89457982j -0.03742876-0.94661484j]


# Проверка комплексных чисел

In [11]:
print("Проверка:") 
for i in range(11): 
    otv = A[i][0]*X[0] + A[i][1]*X[1] + A[i][2]*X[2] + A[i][3]*X[3]+ A[i][4]*X[4] + A[i][5]*X[5]+ A[i][6]*X[6]+ A[i][7]*X[7]+ A[i][8]*X[8]+ A[i][9]*X[9]+ A[i][10]*X[10]
    print(otv, B[i])

Проверка:
(-3.0000000000000027-0.9999999999999998j) (-3-1j)
(-6.439293542825908e-15+1.5543122344752192e-15j) 0j
(3.566591466608315e-15-1.999999999999992j) -2j
(-1.5543122344752192e-15+1.999999999999996j) 2j
(-2.9999999999999973-2.000000000000001j) (-3-2j)
(3.1086244689504383e-15+3.0000000000000013j) 3j
(1.0000000000000047+3.0000000000000004j) (1+3j)
(3.774758283725532e-15+3j) 3j
(-3.000000000000002-2.9999999999999982j) (-3-3j)
(0.999999999999998-1.9984014443252818e-15j) (1+0j)
(4.884981308350689e-15+2.6645352591003757e-15j) 0j


# Решение матриц методом Краймера

In [76]:
import numpy as np
a=np.array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
b=np.array([-2, -3,  0, -1, -1, -3, -3, -2, -3, -2,  0])
det=np.linalg.det(a)
if det==0:
        print("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
        s_0=a[:,0]
        s_1=a[:,1]
        s_2=a[:,2]
        s_3=a[:,3]
        s_4=a[:,4]
        s_5=a[:,5]
        s_6=a[:,6]
        s_7=a[:,7]
        s_8=a[:,8]
        s_9=a[:,9]
        s_10=a[:,10]
        
        a_1=np.column_stack((b,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_1 = np.linalg.det(a_1)
        
        a_2=np.column_stack((s_0,b,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_2 = np.linalg.det(a_2)
        
        a_3=np.column_stack((s_0,s_1,b,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_3 = np.linalg.det(a_3)
        
        a_4=np.column_stack((s_0,s_1,s_2,b,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_4 = np.linalg.det(a_4)
        
        a_5=np.column_stack((s_0,s_1,s_2,s_3,b,s_5,s_6,s_7,s_8,s_9,s_10))
        det_5 = np.linalg.det(a_5)
        
        a_6=np.column_stack((s_0,s_1,s_2,s_3,s_4,b,s_6,s_7,s_8,s_9,s_10))
        det_6 = np.linalg.det(a_6)
        
        a_7=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,b,s_7,s_8,s_9,s_10))
        det_7 = np.linalg.det(a_7)
        
        a_8=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,b,s_8,s_9,s_10))
        det_8 = np.linalg.det(a_8)
        
        a_9=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,b,s_9,s_10))
        det_9 = np.linalg.det(a_9)
        
        a_10=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,b,s_10))
        det_10 = np.linalg.det(a_10)
        
        a_11=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,b))
        det_11 = np.linalg.det(a_11)
        
        x_1=det_1/det
        x_2=det_2/det
        x_3=det_3/det
        x_4=det_4/det
        x_5=det_5/det
        x_6=det_6/det
        x_7=det_7/det
        x_8=det_8/det
        x_9=det_9/det
        x_10=det_10/det
        x_11=det_11/det
        
        print("x1 =", x_1)
        print("x2 =", x_2)
        print("x3 =", x_3)
        print("x4 =", x_4)
        print("x5 =", x_5)
        print("x6 =", x_6)
        print("x7 =", x_7)
        print("x8 =", x_8)
        print("x9 =", x_9)
        print("x10 =", x_10)
        print("x11 =", x_11)

x1 = -5.885133070761342
x2 = 1.030176873094234
x3 = -1.2106021005759635
x4 = 2.0393510115676885
x5 = -3.1404737488504875
x6 = -0.19858595300324283
x7 = 4.46550944412177
x8 = -0.8269089407579485
x9 = 2.8526775990997533
x10 = 4.141198241856627
x11 = 0.22544664464450007


# Проверка метода Крамера


In [78]:
print("Проверка:") 
for i in range(11): 
        otv = a[i][0]*X[0] + a[i][1]*X[1] + a[i][2]*X[2] + a[i][3]*X[3]+ a[i][4]*X[4] + a[i][5]*X[5]+ a[i][6]*X[6]+ a[i][7]*X[7]+ a[i][8]*X[8]+ a[i][9]*X[9]+ [i][10]*X[10]
        print(otv, и[i])

Проверка:


IndexError: list index out of range

# Решение матриц методом Крамера с комплексными числами

In [17]:
import numpy as np
a=np.array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]])
b=np.array([-3.-1.j, 0.+0.j,  0.-2.j,  0.+2.j, -3.-2.j,  0.+3.j,  1.+3.j,  0.+3.j, -3.-3.j,
   1.+0.j,  0.+0.j])
det=np.linalg.det(a)
if det==0:
        print("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
        s_0=a[:,0]
        s_1=a[:,1]
        s_2=a[:,2]
        s_3=a[:,3]
        s_4=a[:,4]
        s_5=a[:,5]
        s_6=a[:,6]
        s_7=a[:,7]
        s_8=a[:,8]
        s_9=a[:,9]
        s_10=a[:,10]
        
        a_1=np.column_stack((b,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_1 = np.linalg.det(a_1)
        
        a_2=np.column_stack((s_0,b,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_2 = np.linalg.det(a_2)
        
        a_3=np.column_stack((s_0,s_1,b,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_3 = np.linalg.det(a_3)
        
        a_4=np.column_stack((s_0,s_1,s_2,b,s_4,s_5,s_6,s_7,s_8,s_9,s_10))
        det_4 = np.linalg.det(a_4)
        
        a_5=np.column_stack((s_0,s_1,s_2,s_3,b,s_5,s_6,s_7,s_8,s_9,s_10))
        det_5 = np.linalg.det(a_5)
        
        a_6=np.column_stack((s_0,s_1,s_2,s_3,s_4,b,s_6,s_7,s_8,s_9,s_10))
        det_6 = np.linalg.det(a_6)
        
        a_7=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,b,s_7,s_8,s_9,s_10))
        det_7 = np.linalg.det(a_7)
        
        a_8=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,b,s_8,s_9,s_10))
        det_8 = np.linalg.det(a_8)
        
        a_9=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,b,s_9,s_10))
        det_9 = np.linalg.det(a_9)
        
        a_10=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,b,s_10))
        det_10 = np.linalg.det(a_10)
        
        a_11=np.column_stack((s_0,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,b))
        det_11 = np.linalg.det(a_11)
        
        x_1=det_1/det
        x_2=det_2/det
        x_3=det_3/det
        x_4=det_4/det
        x_5=det_5/det
        x_6=det_6/det
        x_7=det_7/det
        x_8=det_8/det
        x_9=det_9/det
        x_10=det_10/det
        x_11=det_11/det
        
        print("x1 =", x_1)
        print("x2 =", x_2)
        print("x3 =", x_3)
        print("x4 =", x_4)
        print("x5 =", x_5)
        print("x6 =", x_6)
        print("x7 =", x_7)
        print("x8 =", x_8)
        print("x9 =", x_9)
        print("x10 =", x_10)
        print("x11 =", x_11)

x1 = (1.7232626487107772+0.19162439218609814j)
x2 = (2.1989408114000346-0.49677449377741323j)
x3 = (-1.797688885923673-1.0730360114730026j)
x4 = (-0.12919281666547866+0.822405723927364j)
x5 = (0.07532907933355808-1.2006841550193836j)
x6 = (-3.1733284236859087-1.2493601722719057j)
x7 = (-3.2712459576910575-0.5972381944385831j)
x8 = (0.4350888169034058+2.334948326283931j)
x9 = (-1.824240660526162+2.092474069293538j)
x10 = (0.13168117969821144+2.8945798244373933j)
x11 = (-0.03742875916878426-0.9466148366144876j)


# Проверка решения матриц с комплексными числами методом Крамера

In [79]:
print("Проверка:") 
for i in range(11): 
    otv = a[i][0]*X[0] + a[i][1]*X[1] + a[i][2]*X[2] + a[i][3]*X[3]+ a[i][4]*X[4] + a[i][5]*X[5]+ a[i][6]*X[6]+ a[i][7]*X[7]+ a[i][8]*X[8]+ a[i][9]*X[9]+ a[i][10]*X[10]
    print(otv, b[i])

Проверка:
(10.258253984920193+15.03483980352023j) -2
(5.599340092787642+9.372244968620194j) -3
(13.664582869559464-14.63704764384503j) 0
(-9.739768495920638-3.664943169645177j) -1
(-16.369425870039418+1.0935247688183587j) -1
(-4.464777182989928+7.900369405860612j) -3
(6.250620752010059+5.6678935490047895j) -3
(17.617979438033295+18.301822163239496j) -2
(-6.372881630486997-18.255699432986475j) -3
(3.787816397914818-5.618604922438765j) -2
(-6.489246374746725-13.177328501250674j) 0


# LU-разложение

In [51]:
#Вычислите LU-разложение своих матриц (действительной и комплексной из Задания 01). Прямо проверьте правильность полученных результатов. 
import numpy as np
import scipy.linalg as la
M = np.array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
P, L, U = la.lu(M)
M

array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
       [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
       [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
       [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
       [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
       [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
       [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
       [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
       [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
       [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
       [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [52]:
P

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.66666667,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.53846154,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333,  0.38461538,  0.45652174,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , -0.23076923, -0.5       , -0.9844358 ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.30769231, -0.76086957, -0.17509728, -0.51026393,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.   

In [54]:
U

array([[ 3.        , -2.        ,  0.        ,  1.        , -2.        ,
         1.        ,  3.        ,  0.        ,  2.        , -2.        ,
        -1.        ],
       [ 0.        ,  4.33333333,  1.        , -3.66666667, -0.66666667,
        -0.66666667, -1.        ,  2.        , -1.33333333,  2.33333333,
        -0.33333333],
       [ 0.        ,  0.        ,  3.53846154, -3.30769231, -1.69230769,
        -3.69230769,  1.46153846, -1.92307692, -4.38461538,  1.92307692,
         2.15384615],
       [ 0.        ,  0.        ,  0.        ,  5.58695652,  2.69565217,
         0.60869565, -2.2826087 ,  2.10869565,  2.84782609, -0.10869565,
         0.47826087],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.6536965 ,
        -2.40077821, -3.74708171,  1.57587549,  1.30350195,  4.39299611,
        -1.52918288],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -7.46627566, -5.50733138, -0.6744868 , -1.24926686,  5.07038123,
        -1.826

# Проверка

In [55]:
#Проверка
M

array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
       [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
       [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
       [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
       [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
       [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
       [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
       [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
       [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
       [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
       [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [56]:
P.dot(L.dot(U))

array([[ 0.00000000e+00, -1.00000000e+00, -2.00000000e+00,
        -3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
        -2.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         3.00000000e+00, -3.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
        -1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [-2.00000000e+00,  3.00000000e+00, -1.00000000e+00,
        -1.23904627e-16, -1.19944676e-17,  8.52540223e-18,
        -2.00000000e+00, -3.00000000e+00, -2.00000000e+00,
        -1.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00, -2.00000000e+00,  2.32070030e-17,
         1.00000000e+00, -2.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.00000000e+00,  0.00000000e+00],
       [ 3.00000000e+00, -2.00000000e+00,  0.00000000e+00,
         1.00000000e+00, -2.00000000e+00,  1.00000000e+00,
  

# LU разложение матрицы с комплексными числами 

In [ ]:
import numpy as np
import scipy.linalg as la
M = np.array([[-3.-2.j, -3.+3.j,  0.-2.j, -1.+1.j,  1.-2.j,  2.-3.j, -2.+0.j,  2.-3.j, -3.+1.j,
  -3.-1.j,  1.+2.j],
 [ 2.+0.j,  1.-1.j, -2.+0.j,  0.-2.j,  0.+1.j,  0.-2.j,  2.+3.j,  1.+3.j,  0.-3.j,
  -1.+1.j,  2.-1.j],
 [ 3.-1.j, -2.-1.j,  3.+0.j, -2.+1.j,  1.+1.j, -1.-2.j, -3.+1.j,  1.+1.j,  3.+1.j,
  -2.-1.j,  1.+0.j],
 [ 2.+3.j,  3.-3.j, -3.-3.j,  0.+1.j, -3.-1.j,  3.+0.j,  1.+3.j,  1.-1.j, 0.-2.j,
   0.+2.j, -1.+2.j],
 [-2.+0.j,  0.-3.j,  1.-1.j,  0.-3.j,  3.-2.j, -1.+0.j,  0.-3.j, -1.+1.j, -3.-3.j,  
  -1.+2.j, -2.+0.j],
 [-3.+0.j,  2.+3.j, 2.-1.j,  1.-2.j,  1.+2.j,  0.-1.j, -1.+0.j, -2.+0.j,  0.+2.j,
   2.+0.j,  3.+3.j],
 [ 0.+0.j,  0.+2.j,  2.+0.j,  2.+1.j,  1.-1.j, -1.+3.j,  0.-2.j, -1.+2.j,  2.-3.j,
  -3.+0.j, -3.+3.j],
 [-2.-1.j, -3.+1.j,  2.+1.j, -1.-1.j,  0.+1.j, -1.+1.j, -2.+2.j,  3.+1.j,  0.-3.j,
   0.+2.j,  0.-2.j],
 [-2.+2.j, -3.-2.j,  3.+3.j, -1.-2.j, -3.+3.j, -3.+2.j, -2.+3.j,  0.+3.j,  2.-2.j,
   2.+2.j,  2.-3.j],
 [-3.+1.j,  1.+0.j, -3.+1.j,  2.-1.j,  2.+3.j,  0.+1.j, -3.+0.j, -3.+0.j,  2.+3.j,
   2.+3.j, -2.+2.j],
 [ 2.+3.j,  3.+2.j, -1.+2.j,  3.+3.j,  1.-2.j,  1.+2.j,  0.-3.j, -1.+0.j, -2.+2.j,
   1.+3.j,  2.+3.j]])
P, L, U = la.lu(M)
M

In [61]:
P

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.66666667,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.53846154,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333,  0.38461538,  0.45652174,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        , -0.23076923, -0.5       , -0.9844358 ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.33333333, -0.30769231, -0.76086957, -0.17509728, -0.51026393,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.   

In [63]:
U

array([[ 3.        , -2.        ,  0.        ,  1.        , -2.        ,
         1.        ,  3.        ,  0.        ,  2.        , -2.        ,
        -1.        ],
       [ 0.        ,  4.33333333,  1.        , -3.66666667, -0.66666667,
        -0.66666667, -1.        ,  2.        , -1.33333333,  2.33333333,
        -0.33333333],
       [ 0.        ,  0.        ,  3.53846154, -3.30769231, -1.69230769,
        -3.69230769,  1.46153846, -1.92307692, -4.38461538,  1.92307692,
         2.15384615],
       [ 0.        ,  0.        ,  0.        ,  5.58695652,  2.69565217,
         0.60869565, -2.2826087 ,  2.10869565,  2.84782609, -0.10869565,
         0.47826087],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.6536965 ,
        -2.40077821, -3.74708171,  1.57587549,  1.30350195,  4.39299611,
        -1.52918288],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -7.46627566, -5.50733138, -0.6744868 , -1.24926686,  5.07038123,
        -1.826

In [64]:
#Проверка
M

array([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
       [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
       [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
       [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
       [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
       [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
       [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
       [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
       [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
       [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
       [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [65]:
P.dot(L.dot(U))

array([[ 0.00000000e+00, -1.00000000e+00, -2.00000000e+00,
        -3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
        -2.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         3.00000000e+00, -3.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  2.00000000e+00,
         3.00000000e+00,  1.00000000e+00, -1.00000000e+00,
        -1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [-2.00000000e+00,  3.00000000e+00, -1.00000000e+00,
        -1.23904627e-16, -1.19944676e-17,  8.52540223e-18,
        -2.00000000e+00, -3.00000000e+00, -2.00000000e+00,
        -1.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00, -2.00000000e+00,  2.32070030e-17,
         1.00000000e+00, -2.00000000e+00,  2.00000000e+00,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.00000000e+00,  0.00000000e+00],
       [ 3.00000000e+00, -2.00000000e+00,  0.00000000e+00,
         1.00000000e+00, -2.00000000e+00,  1.00000000e+00,
  

In [57]:
#Вычислите QR-разложение своих матриц (действительной и комплексной из Задания 01). Проверьте правильность полученных результатов. 
A = np.matrix([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
A

matrix([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
        [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
        [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
        [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
        [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
        [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
        [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
        [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
        [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
        [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
        [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [58]:
q

matrix([[-3.17999364e-01-2.11999576e-01j,
          1.98057233e-01-1.90811237e-01j,
          1.61224106e-01+1.84234060e-01j,
         -2.73839874e-02+3.97856446e-02j,
         -5.50850493e-02+2.94433026e-01j,
         -3.60725937e-01+4.65001025e-01j,
          4.81128412e-03-5.45860546e-02j,
         -2.90057068e-01-1.39397198e-01j,
          1.58246678e-01+2.57592878e-01j,
          1.64805140e-01+6.55839285e-02j,
         -6.68435197e-02-2.14617967e-01j],
        [ 2.11999576e-01-7.43963956e-20j,
         -9.05749542e-02+8.45366239e-03j,
          1.92465137e-01+1.44700179e-02j,
          1.12453248e-01+5.28773833e-01j,
         -2.53483673e-03-8.34926645e-02j,
          3.09411279e-01+2.11093351e-02j,
         -6.29979206e-02-1.81293233e-01j,
         -2.34447689e-01-3.76035859e-01j,
         -1.77897390e-01+3.87590959e-02j,
          3.74405478e-01-2.06590373e-02j,
          3.23340277e-01-5.11193502e-02j],
        [ 3.17999364e-01-1.05999788e-01j,
          1.90811237e-01-4.95143

In [59]:
r

matrix([[ 9.43398113+0.00000000e+00j,  0.74199852-4.34599131e+00j,
         -0.52999894+1.27199746e+00j,  0.31799936+1.16599767e+00j,
         -1.16599767-1.05999788e-01j,  2.86199428-7.41998516e-01j,
          2.75599449-1.98805509e-16j,  1.8019964 +1.80199640e+00j,
          0.95399809-8.47998304e-01j,  1.27199746-2.75599449e+00j,
          1.27199746-5.29998940e-01j],
        [ 0.        +0.00000000e+00j, -9.30385929+0.00000000e+00j,
          2.80299292+1.89603571e+00j, -4.92606984+6.71462327e-01j,
          0.17148858+2.02646364e+00j, -1.46731426+1.17022841e+00j,
         -0.42509845+1.82478341e+00j,  3.27881334+1.20042006e+00j,
         -1.46248359-1.87912838e+00j,  0.95888685-1.45282227e+00j,
         -2.2305592 -1.49025991e+00j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         -8.40531992+0.00000000e+00j,  0.5686856 +2.87908572e+00j,
         -1.68868352-3.69487352e-01j,  0.43368358-2.63939613e+00j,
          2.47553128-4.26487177e-01j, -1.45103239-3

In [60]:
#Проверка
q.dot(r)

matrix([[-3.00000000e+00-2.00000000e+00j,
         -3.00000000e+00+3.00000000e+00j,
          1.22124533e-15-2.00000000e+00j,
         -1.00000000e+00+1.00000000e+00j,
          1.00000000e+00-2.00000000e+00j,
          2.00000000e+00-3.00000000e+00j,
         -2.00000000e+00-6.10622664e-16j,
          2.00000000e+00-3.00000000e+00j,
         -3.00000000e+00+1.00000000e+00j,
         -3.00000000e+00-1.00000000e+00j,
          1.00000000e+00+2.00000000e+00j],
        [ 2.00000000e+00-7.01854192e-19j,
          1.00000000e+00-1.00000000e+00j,
         -2.00000000e+00-7.35522754e-16j,
          1.63757896e-15-2.00000000e+00j,
          1.11022302e-16+1.00000000e+00j,
         -4.44089210e-16-2.00000000e+00j,
          2.00000000e+00+3.00000000e+00j,
          1.00000000e+00+3.00000000e+00j,
         -1.11022302e-15-3.00000000e+00j,
         -1.00000000e+00+1.00000000e+00j,
          2.00000000e+00-1.00000000e+00j],
        [ 3.00000000e+00-1.00000000e+00j,
         -2.00000000e+00-1.00000

# QR разложение матрицы с комплексными числами

In [66]:
#Вычислите QR-разложение своих матриц (действительной и комплексной из Задания 01). Проверьте правильность полученных результатов. 
A = np.matrix([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
 [ 1,  1,  2,  3,  1, -1, -1,  2, 1,  1,  1],
 [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
 [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
 [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
 [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
 [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
 [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
 [-3, 1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
 [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
 [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])
A

matrix([[ 0, -1, -2, -3,  1, -1, -2,  0,  1,  3, -3],
        [ 1,  1,  2,  3,  1, -1, -1,  2,  1,  1,  1],
        [-2,  3, -1,  0,  0,  0, -2, -3, -2, -1,  1],
        [-1, -2,  0,  1, -2,  2, -1,  0,  0, -2,  0],
        [ 3, -2,  0,  1, -2,  1,  3,  0,  2, -2, -1],
        [ 3,  0,  0,  3,  0, -1,  3,  3,  2, -2,  0],
        [ 2,  3,  1, -3, -2,  0,  1,  2,  0,  1, -1],
        [ 1, -2, -3,  3, -1, -3, -3, -1,  2,  0, -3],
        [-3,  1, -1,  2,  3,  3, -3, -3,  2, -3,  3],
        [-2,  3,  3, -3,  3, -3,  0, -1,  2, -1, -3],
        [ 1, -3,  3, -1, -2, -3,  3, -3, -3,  0,  2]])

In [67]:
q

matrix([[-3.17999364e-01-2.11999576e-01j,
          1.98057233e-01-1.90811237e-01j,
          1.61224106e-01+1.84234060e-01j,
         -2.73839874e-02+3.97856446e-02j,
         -5.50850493e-02+2.94433026e-01j,
         -3.60725937e-01+4.65001025e-01j,
          4.81128412e-03-5.45860546e-02j,
         -2.90057068e-01-1.39397198e-01j,
          1.58246678e-01+2.57592878e-01j,
          1.64805140e-01+6.55839285e-02j,
         -6.68435197e-02-2.14617967e-01j],
        [ 2.11999576e-01-7.43963956e-20j,
         -9.05749542e-02+8.45366239e-03j,
          1.92465137e-01+1.44700179e-02j,
          1.12453248e-01+5.28773833e-01j,
         -2.53483673e-03-8.34926645e-02j,
          3.09411279e-01+2.11093351e-02j,
         -6.29979206e-02-1.81293233e-01j,
         -2.34447689e-01-3.76035859e-01j,
         -1.77897390e-01+3.87590959e-02j,
          3.74405478e-01-2.06590373e-02j,
          3.23340277e-01-5.11193502e-02j],
        [ 3.17999364e-01-1.05999788e-01j,
          1.90811237e-01-4.95143

In [68]:
r

matrix([[ 9.43398113+0.00000000e+00j,  0.74199852-4.34599131e+00j,
         -0.52999894+1.27199746e+00j,  0.31799936+1.16599767e+00j,
         -1.16599767-1.05999788e-01j,  2.86199428-7.41998516e-01j,
          2.75599449-1.98805509e-16j,  1.8019964 +1.80199640e+00j,
          0.95399809-8.47998304e-01j,  1.27199746-2.75599449e+00j,
          1.27199746-5.29998940e-01j],
        [ 0.        +0.00000000e+00j, -9.30385929+0.00000000e+00j,
          2.80299292+1.89603571e+00j, -4.92606984+6.71462327e-01j,
          0.17148858+2.02646364e+00j, -1.46731426+1.17022841e+00j,
         -0.42509845+1.82478341e+00j,  3.27881334+1.20042006e+00j,
         -1.46248359-1.87912838e+00j,  0.95888685-1.45282227e+00j,
         -2.2305592 -1.49025991e+00j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
         -8.40531992+0.00000000e+00j,  0.5686856 +2.87908572e+00j,
         -1.68868352-3.69487352e-01j,  0.43368358-2.63939613e+00j,
          2.47553128-4.26487177e-01j, -1.45103239-3

In [69]:
#Проверка
q.dot(r)

matrix([[-3.00000000e+00-2.00000000e+00j,
         -3.00000000e+00+3.00000000e+00j,
          1.22124533e-15-2.00000000e+00j,
         -1.00000000e+00+1.00000000e+00j,
          1.00000000e+00-2.00000000e+00j,
          2.00000000e+00-3.00000000e+00j,
         -2.00000000e+00-6.10622664e-16j,
          2.00000000e+00-3.00000000e+00j,
         -3.00000000e+00+1.00000000e+00j,
         -3.00000000e+00-1.00000000e+00j,
          1.00000000e+00+2.00000000e+00j],
        [ 2.00000000e+00-7.01854192e-19j,
          1.00000000e+00-1.00000000e+00j,
         -2.00000000e+00-7.35522754e-16j,
          1.63757896e-15-2.00000000e+00j,
          1.11022302e-16+1.00000000e+00j,
         -4.44089210e-16-2.00000000e+00j,
          2.00000000e+00+3.00000000e+00j,
          1.00000000e+00+3.00000000e+00j,
         -1.11022302e-15-3.00000000e+00j,
         -1.00000000e+00+1.00000000e+00j,
          2.00000000e+00-1.00000000e+00j],
        [ 3.00000000e+00-1.00000000e+00j,
         -2.00000000e+00-1.00000