In [ ]:
##77e №1

In [1]:
import numpy as np
A = np.array([[1, 0, 2, -1], 
              [2, 0, 0, -3], 
              [-1, -3, 3, 2],
              [-3, 3, 2, 3]])
A

array([[ 1,  0,  2, -1],
       [ 2,  0,  0, -3],
       [-1, -3,  3,  2],
       [-3,  3,  2,  3]])

In [2]:
R1 = np.array([[0, 2, 2, 1/2], 
               [2, 0, 0, -3], 
               [1, -3, -3, 2],
               [-3, 3, 2, 3]])
print(R1)

[[ 0.   2.   2.   0.5]
 [ 2.   0.   0.  -3. ]
 [ 1.  -3.  -3.   2. ]
 [-3.   3.   2.   3. ]]


In [3]:
R2 = np.array([[0, 0, 2, 1/2], 
               [2, 0, 0, -3], 
               [0, -3, 3, 1/2],
               [0, 0, 5, -1]])
print(R2)


[[ 0.   0.   2.   0.5]
 [ 2.   0.   0.  -3. ]
 [ 0.  -3.   3.   0.5]
 [ 0.   0.   5.  -1. ]]


In [4]:
R3 = np.array([[0, 0, 2, 0.5], 
               [2, 0, 0, -3], 
               [0, -3, 0, -1/4],
               [0, 0, 0, -2/4]])
print(R3)

[[ 0.    0.    2.    0.5 ]
 [ 2.    0.    0.   -3.  ]
 [ 0.   -3.    0.   -0.25]
 [ 0.    0.    0.   -0.5 ]]


In [5]:
U = R3.dot(R2.dot(R1.dot(A)))
U,

(array([[-138.  ,  183.  ,  -10.5 ,  137.5 ],
        [  56.  , -153.  ,   57.  ,  -60.  ],
        [ -67.  ,   36.  ,   17.25,   57.75],
        [  16.  ,  -36.  ,   10.5 ,  -16.5 ]]),)

In [6]:
T = R3.dot(R2.dot(R1))
T

array([[ -5.  , -24.  , -24.5 ,  36.5 ],
       [-23.  ,  45.  ,  41.  , -10.  ],
       [-29.  ,  19.5 ,  10.25,  22.25],
       [ -4.  ,   9.  ,   8.5 ,  -3.5 ]])

In [7]:
L = np.linalg.inv(T)
L

array([[-0.05392157,  0.5462963 , -0.08823529, -2.68409586],
       [-0.21078431,  0.62037037,  0.04901961, -3.65904139],
       [ 0.20588235, -0.27777778, -0.11764706,  2.19281046],
       [ 0.01960784,  0.2962963 , -0.05882353, -1.30174292]])

In [8]:
L.dot(U)

array([[ 1.00000000e+00, -1.77635684e-15,  2.00000000e+00,
        -1.00000000e+00],
       [ 2.00000000e+00, -1.77635684e-14,  7.54951657e-15,
        -3.00000000e+00],
       [-1.00000000e+00, -3.00000000e+00,  3.00000000e+00,
         2.00000000e+00],
       [-3.00000000e+00,  3.00000000e+00,  2.00000000e+00,
         3.00000000e+00]])

In [9]:
##77e №2

In [10]:
A = np.matrix("1 0 2 -1; 2 0 0 -3; -1 -3 3 2; -3, 3, 2, 3")
A

matrix([[ 1,  0,  2, -1],
        [ 2,  0,  0, -3],
        [-1, -3,  3,  2],
        [-3,  3,  2,  3]])

In [11]:
q, r = np.linalg.qr(A)

In [12]:
q

matrix([[-0.25819889, -0.10127394, -0.76866834,  0.57639042],
        [-0.51639778, -0.20254787, -0.36172628, -0.74930754],
        [ 0.25819889,  0.86082846, -0.37303022, -0.23055617],
        [ 0.77459667, -0.45573272, -0.37303022, -0.23055617]])

In [13]:
r

matrix([[-3.87298335,  1.54919334,  1.80739223,  4.64758002],
        [ 0.        , -3.94968353,  1.46847208,  1.06337634],
        [ 0.        ,  0.        , -3.40248778, -0.01130395],
        [ 0.        ,  0.        ,  0.        ,  0.51875138]])

In [14]:
q.dot(r)

matrix([[ 1.00000000e+00, -6.10852591e-16,  2.00000000e+00,
         -1.00000000e+00],
        [ 2.00000000e+00,  3.14451740e-16, -1.74757591e-16,
         -3.00000000e+00],
        [-1.00000000e+00, -3.00000000e+00,  3.00000000e+00,
          2.00000000e+00],
        [-3.00000000e+00,  3.00000000e+00,  2.00000000e+00,
          3.00000000e+00]])

In [15]:
##77e №3

In [16]:
A = np.matrix("1 0 2 -1; 2 0 0 -3; -1 -3 3 2; -3, 3, 2, 3")
A

matrix([[ 1,  0,  2, -1],
        [ 2,  0,  0, -3],
        [-1, -3,  3,  2],
        [-3,  3,  2,  3]])

In [17]:
u, s, v = np.linalg.svd(A)
u

matrix([[-0.07387554,  0.24789117, -0.73005361,  0.63254573],
        [-0.49050331,  0.03965211, -0.53315712, -0.68816982],
        [ 0.39952239,  0.87856736,  0.03292156, -0.25964866],
        [ 0.77092851, -0.4063214 , -0.426241  , -0.2426742 ]])

In [18]:
s

array([6.62154184, 4.55088007, 2.88937899, 0.31010212])

In [19]:
v

matrix([[-0.56892944,  0.16827174,  0.39155127,  0.7033431 ],
        [ 0.14669519, -0.84701557,  0.50953697,  0.03764613],
        [-0.19054835, -0.47674178, -0.76619389,  0.38646542],
        [ 0.78644208,  0.16421488,  0.00257036,  0.59542903]])